### ISSUE TITLE
Support for EPiServer.Framework ≥ 10.0

### ISSUE THREAD

**Issue by pritchahal** [khurramkhang/Maxmind.GeoIP#1]
Hi,

We want to upgrade to Episerver version 10 and our application has a dependency on the PixieEPiServerExtensionMaxMindGeoIP2 Nuget package. The fact that the latest version (1.0.3) of the package does not support Episerver version 10 is preventing us performing the upgrade.

Are you able to provide an ETA for when the Nuget package will be updated to support Episerver version 10?

Thanks

**Comment by khurramkhang** [comment]
Hi, Thanks, I'll have a look in weekend and get back to you.
Regards
/K

**Comment by khurramkhang** [comment]
Hi, 1.0.4 is available to allow installation on 10. I will appreciate if you could provide feedback after upgrade.
Best Regards
/K

**Comment by pritchahal** [comment]
Upgrade was seamless and everything appears to be working fine. Thanks for the quick response.

/Prit
