### ISSUE TITLE
PixieEPiServerExtensionMaxMindGeoIP2 1.0.4 not compatible with EPiServer.Framework 10.4.1

### ISSUE THREAD

**Issue by pritchahal** [khurramkhang/Maxmind.GeoIP#2]
Hi,

The latest version of Episerver.Frameowork (10.4.1) has the following dependency constraint on Newtonsoft.Json:

Newtonsoft.Json (>= 9.0.1 && < 10.0.0)

PixieEPiServerExtensionMaxMindGeoIP2 1.0.4 has the constraint:

Newtonsoft.Json (>= 8.0.3 && < 9.0.0)

which makes it incompatible.

I asked you recently to upgrade your package for Episerver v10 and received a quick response. Can you do the same again to make it compatible with EPiServer.Framework 10.4.1?

Thanks,
Prit

**Comment by khurramkhang** [comment]
Hi Prit, Thanks for raising this issue. I have upgraded the nuget package to let you install framework 10.4.1 to remove your blocker. Version 1.0.5 will be available probably tomorrow on nuget.episerver.com. I am afraid I haven't tested myself yet with 10.4.1. I'll appriciate your feed back, If you find any issue please let me know.

Best Regards
Khurram

**Comment by pritchahal** [comment]
Everything appears to be working fine. Once again, thanks for the quick response.

/Prit

**Comment by khurramkhang** [comment]
Thanks Prit for your feedback
/K
