### ISSUE TITLE
PixieEPiServerExtensionMaxMindGeoIP2 1.0.6 incompatible with EPiServer Framework >11

### ISSUE THREAD

**Issue by tomdickie** [khurramkhang/Maxmind.GeoIP#4]
I'm attempting to upgrade to the latest version of EPiServer 11.3.1, but the EPiServer Framework dependencies on this nuget package prevent this. <11.0.0.

Also, version 11+ of EPiServer has changed the .net version to 4.6.1.

Would you be able to update this to support the updated version of EPiServer?

Thank you.

**Comment by khurramkhang** [comment]
Thanks for reporting,  I will update.

**Comment by khurramkhang** [comment]
http://nuget.episerver.com/en/OtherPages/Package/?packageId=PixieEPiServerExtensionMaxMindGeoIP2&packageVersion=2.0.0 is available for V11
