### ISSUE TITLE
Region Functionality

### ISSUE THREAD

**Issue by eddydugan** [khurramkhang/Maxmind.GeoIP#6]
Hi,

Thank you for this code!
In the US, a common use of this is to recognize when someone from a particular state (region) is coming to your site.
I altered your mapping (in GeolocationMaxmindService) from your CityResponse (dbResult) to the GeoLocationResult (result) to add:
-  result.Region = dbResult.MostSpecificSubdivision.IsoCode;
- result.RegionName = dbResult.MostSpecificSubdivision.Name;

This worked to activate the existing Episerver VG criterion for state.

Thanks!
Eddy

**Comment by khurramkhang** [comment]
Thanks I will update those
